piVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "citrix-k8s-ingress-controller-01"
  labels:
    app.kubernetes.io/name: "citrix-k8s-ingress-controller-01"
    app.kubernetes.io/version: "3"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "citrix-k8s-ingress-controller-01"
  componentKinds:
    - group: core
      kind: Service
    - group: core
      kind: Endpoints
    - group: core
      kind: Ingresses
    - group: core
      kind: Pods
    - group: core
      kind: Secrets
    - group: core
      kind: Nodes
    - group: apps
      kind: Deployment
    - group: extensions
      kind: Ingresses
    - group: extensions
      kind: ingresses/status
    - group: citrix.com
      kind: rewritepolicies
#  assemblyPhase:
  descriptor:
    version: "1.1.1"
    description: "Citrix NetScaler Ingress Controller is built around Kubernetes Ingress. 
                  This controller automatically configures one or more Citrix NetScaler ADC 
                  based on Ingress resource configuration."
    icons:
      - src: "https://raw.githubusercontent.com/citrix/citrix-k8s-ingress-controller/gh-pages/icon.png"
        type: "image/png"
    type: "citrix-k8s-ingress-controller"
    maintainers:
      - name: 
        email: 
    owners:
      - 
    keywords:
      - "citrix"
      - "ingress"
      - "controller"
    links:
      - description: GitHub
        url: "https://github.com/citrix/citrix-k8s-ingress-controller"
      - description:
        url:
