application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  cicimage.image:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  nsIP:
    type: string
    title: NS IP of the VPX
    description: NS IP of the VPX
  nsVIP:
    type: string
    title: Virtual IP of the VPX
    description: Virtual IP of the VPX
  serviceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['']
            resources: ['services', 'endpoints', 'ingresses', 'pods', 'secrets', 'nodes']
            verbs: ['*']
          - apiGroups: ['extensions']
            resources: ['ingresses', 'ingresses/status']
            verbs: ['*']
          - apiGroups: ['citrix.com']
            resources: ['rewritepolicies']
            verbs: ['*']
          - apiGroups: ['apps']
            resources: ['deployments']
            verbs: ['*']
  loginFileName:
    type: string
    title: Secret file Name for Citrix ADC
    description: Secret file Name for Citrix ADC
    default: nslogin
  nsPort:
    type: integer
    title: NITRO port
    description: nsPort is port for Citrix ADC NITRO
    default: 443
  nsProtocol:
    type: string
    title: protocol for NITRO
    description: protocol used for NetScaler ADC NITRO
    default: HTTPS
  logLevel:
    type: string
    title: Log level of Citrix ingress controller
    description: Level of logs generated by Citrix ingress controller
    default: DEBUG
  nodeWatch:
    type: string
    title: Automatic route configuration
    description: Automatic route configuration on Citrix ADC VPX towards the pod network
    default: false

required:
- name
- namespace
- cicimage.image
- nsIP
- nsVIP
