application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  cicimage.image:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  nsIP:
    type: string
    title: NS IP of the VPX
    description: NS IP of the VPX
    default: 127.0.1.1
  nsVIP:
    type: string
    title: Virtual IP of the VPX
    description: Virtual IP of the VPX
    default: 127.0.2.2
required:
- name
- namespace
- cicimage.image
- nsIP
- nsVIP
