application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  license.accept:
    type: string
    title: EULA License
    description: Accept EULA license
    default: "no"
  cic.image:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  nsIP:
    type: string
    title: NS IP of the VPX
    description: NS IP of the VPX
  nsVIP:
    type: string
    title: Virtual IP of the VPX
    description: Virtual IP of the VPX
  serviceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['']
            resources: ['services', 'endpoints', 'ingresses', 'pods', 'secrets', 'nodes']
            verbs: ['*']
          - apiGroups: ['extensions']
            resources: ['ingresses', 'ingresses/status']
            verbs: ['*']
          - apiGroups: ['citrix.com']
            resources: ['rewritepolicies']
            verbs: ['*']
          - apiGroups: ['apps']
            resources: ['deployments']
            verbs: ['*']
  loginFileName:
    type: string
    title: Secret file Name for Citrix ADC
    description: Secret file Name for Citrix ADC
  nsPort:
    type: integer
    title: NITRO port
    description: nsPort is port for Citrix ADC NITRO
    default: 443
  nsProtocol:
    type: string
    title: protocol for NITRO
    description: protocol used for NetScaler ADC NITRO
    default: HTTPS
  logLevel:
    type: string
    title: Log level of Citrix ingress controller
    description: Level of logs generated by Citrix ingress controller
    default: DEBUG
  ingressClass:
    type: string
    title: Ingress Class
    description: Please provide name of the Ingress Class.
  nodeWatch:
    type: boolean
    title: Automatic route configuration
    description: Automatic route configuration on Citrix ADC VPX towards the pod network
    default: false
  exporter.image:
    type: string
    default: $REGISTRY/netscaler-metrics-exporter:$TAG
    x-google-marketplace:
      type: IMAGE
  exporter.required:
    type: boolean
    title: Prometheus Exporter
    description: Set if exporter is needed with Citrix ADC CPX
    default: false
  exporter.ports.containerPort:
    type: integer
    title: Prometheus Exporter Port
    description: Specify on which port metrics collected by the exporter should be exposed.
    default: 8888

required:
- name
- namespace
- serviceAccount
- cic.image
- nsIP
- nsVIP
- exporter.required
- exporter.image
