apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cpx-ingress
  annotations:
   kubernetes.io/ingress.class: {{- range .Values.ingressClass}} {{ . | quote }} {{- end }}
spec:
  rules:
  - host: citrix-ingress-gke.com
    http:
      paths:
      - path: /
        backend:
          serviceName: apache
          servicePort: 80
---
